# Generated by Django 3.2.4 on 2021-06-15 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("author", models.CharField(max_length=1024)),
                ("time", models.DateTimeField()),
                ("score", models.IntegerField()),
                ("title", models.CharField(max_length=1024)),
                ("url", models.CharField(max_length=1024)),
                ("type", models.CharField(max_length=1024)),
            ],
        ),
    ]
